import type { KnowledgeArticleMetadata } from "./types";
import { links } from "@/config/links";
import { validateKnowledgeRegistry } from "@/lib/knowledge/validate";

/**
 * Central registry of knowledge article metadata.
 * Markdown bodies live in content/knowledge/articles/{slug}.md
 */
export const knowledgeArticles: readonly KnowledgeArticleMetadata[] = [
  {
    id: "what-is-the-portal-genie",
    slug: "what-is-the-portal-genie",
    title: "What is The Portal Genie?",
    description:
      "Learn what The Portal Genie is and how it helps businesses deliver a connected client portal experience alongside their accounting software.",
    category: "getting-started",
    summary:
      "The Portal Genie is client portal software that brings documents, communication, payments and self-service together in one branded experience — working alongside Xero, QuickBooks Online and Sage Business Cloud.",
    keywords: [
      "portal genie",
      "client portal",
      "customer experience",
      "accounting software",
    ],
    relatedArticles: [
      "how-the-client-portal-works",
      "client-portal-features",
      "core-vs-pro",
    ],
    relatedPages: [links.features, links.whyThePortalGenie, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "how-the-client-portal-works",
    slug: "how-the-client-portal-works",
    title: "How The Portal Genie Client Portal Works",
    description:
      "Understand how your business, accounting software and clients connect through The Portal Genie Client Portal.",
    category: "getting-started",
    summary:
      "Your team continues working in your accounting software while clients access invoices, documents, payments and communication through a secure, branded Client Portal.",
    keywords: [
      "client portal",
      "how it works",
      "accounting integration",
      "customer access",
    ],
    relatedArticles: [
      "what-is-the-portal-genie",
      "client-portal-access",
      "client-portal-features",
    ],
    relatedPages: [links.features, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-access",
    slug: "client-portal-access",
    title: "How Clients Access Your Portal — No Registration Required",
    description:
      "Clients access your Client Portal through a secure email OTP process — no separate registration or Portal Genie password required.",
    category: "getting-started",
    summary:
      "Clients open your Client Portal Link, enter their email address, receive a secure one-time passcode and access their portal — no separate registration required.",
    keywords: [
      "client access",
      "OTP login",
      "no registration",
      "client portal link",
    ],
    relatedArticles: [
      "add-client-login-to-your-website",
      "client-portal-security",
      "how-the-client-portal-works",
    ],
    relatedPages: [links.features, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "add-client-login-to-your-website",
    slug: "add-client-login-to-your-website",
    title: "Add a Client Login Button to Your Existing Website",
    description:
      "Use your Client Portal Link to add a Client Login button to your website — no need to build your own login system.",
    category: "getting-started",
    summary:
      "Every Portal Genie account includes a Client Portal Link you can add to your website as a Client Login button or share directly with clients.",
    keywords: [
      "client login",
      "client portal link",
      "website login",
      "customer login",
    ],
    relatedArticles: [
      "client-portal-access",
      "client-portal-features",
      "how-the-client-portal-works",
    ],
    relatedPages: [links.features, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-features",
    slug: "client-portal-features",
    title: "What Can Clients Do in the Client Portal?",
    description:
      "An overview of what clients can access and do in your Portal Genie Client Portal — from invoices and documents to payments and the Notice Board.",
    category: "customer-portal",
    summary:
      "Clients can view accounting documents, download files, make payments, read your Notice Board, upload documents on Pro and exchange document notes — all in one branded portal.",
    keywords: [
      "client portal features",
      "invoices",
      "documents",
      "pay now",
      "notice board",
    ],
    relatedArticles: [
      "customise-client-portal",
      "notice-board",
      "client-portal-payments",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "customise-client-portal",
    slug: "customise-client-portal",
    title: "Customising Your Client Portal",
    description:
      "Tailor your Client Portal with your branding, folders, document statuses, Notice Board and welcome messaging.",
    category: "customer-portal",
    summary:
      "Customise your Client Portal with your logo, brand colours, folders, document statuses and Notice Board to deliver a professional, on-brand client experience.",
    keywords: [
      "customise portal",
      "branding",
      "folders",
      "document statuses",
      "notice board",
    ],
    relatedArticles: [
      "client-portal-branding",
      "notice-board",
      "client-portal-folders",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-folders",
    slug: "client-portal-folders",
    title: "Organising Client Documents with Folders",
    description:
      "Use standard and custom folders to organise documents in your Client Portal and help clients find what they need quickly.",
    category: "customer-portal",
    summary:
      "Organise client documents with standard accounting folders and custom folders, controlling visibility, order and upload permissions.",
    keywords: [
      "document folders",
      "client portal organisation",
      "custom folders",
      "document visibility",
    ],
    relatedArticles: [
      "share-client-documents",
      "customise-client-portal",
      "client-portal-features",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "notice-board",
    slug: "notice-board",
    title: "Using the Notice Board",
    description:
      "Share announcements, promotions and important messages with clients through the Client Portal Notice Board.",
    category: "customer-portal",
    summary:
      "The Notice Board is your Client Portal display space for customer announcements, promotions and important messages — with engagement tracking.",
    keywords: [
      "notice board",
      "client announcements",
      "portal display",
      "client engagement",
    ],
    relatedArticles: [
      "customise-client-portal",
      "client-portal-analytics",
      "client-portal-features",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "share-client-documents",
    slug: "share-client-documents",
    title: "Sharing Documents Securely with Clients",
    description:
      "Share accounting documents and uploaded files with clients through your secure Client Portal.",
    category: "documents",
    summary:
      "Share invoices, statements, quotes, credit notes and custom documents with clients through secure portal access organised in folders.",
    keywords: [
      "document sharing",
      "secure documents",
      "invoices",
      "client documents",
    ],
    relatedArticles: [
      "client-portal-folders",
      "new-document-notifications",
      "accounting-integrations",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-document-uploads",
    slug: "client-document-uploads",
    title: "Client Document Uploads",
    description:
      "Let clients upload documents to your portal on Pro — you control which folders accept uploads.",
    category: "documents",
    summary:
      "On Pro, clients can upload documents to permitted folders so your team can receive and review files without email attachments.",
    keywords: [
      "client uploads",
      "document uploads",
      "receive documents",
      "pro feature",
    ],
    relatedArticles: [
      "share-client-documents",
      "core-vs-pro",
      "client-portal-folders",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "document-notes",
    slug: "document-notes",
    title: "Document Notes and Client Communication",
    description:
      "Exchange document notes with clients on Pro — keeping conversations tied to the documents they relate to.",
    category: "communication",
    summary:
      "Document notes let clients and your team exchange messages attached to specific documents, keeping communication in context.",
    keywords: [
      "document notes",
      "client communication",
      "portal messaging",
      "pro feature",
    ],
    relatedArticles: [
      "new-document-notifications",
      "client-portal-features",
      "core-vs-pro",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "new-document-notifications",
    slug: "new-document-notifications",
    title: "Notify Clients When New Documents Are Available",
    description:
      "Automatically notify clients by email when new documents are assigned and available in their portal.",
    category: "communication",
    summary:
      "Enable new document notifications so clients receive an email when documents are assigned and ready to view in their Client Portal.",
    keywords: [
      "document notifications",
      "client email",
      "new documents",
      "portal alerts",
    ],
    relatedArticles: [
      "share-client-documents",
      "scheduled-client-notifications",
      "document-notes",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "accounting-integrations",
    slug: "accounting-integrations",
    title: "Connecting Portal Genie to Your Accounting Software",
    description:
      "Connect The Portal Genie to Xero, QuickBooks Online or Sage Business Cloud to bring accounting documents into your Client Portal.",
    category: "integrations",
    summary:
      "Portal Genie integrates with Xero, QuickBooks Online and Sage Business Cloud to surface invoices, statements, quotes and credit notes in your Client Portal.",
    keywords: [
      "accounting integration",
      "xero",
      "quickbooks",
      "sage",
      "connected app",
    ],
    relatedArticles: [
      "xero-client-portal",
      "quickbooks-client-portal",
      "sage-client-portal",
    ],
    relatedPages: [links.features, links.whyThePortalGenie],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "xero-client-portal",
    slug: "xero-client-portal",
    title: "Portal Genie for Xero",
    description:
      "Deliver a secure Client Portal connected to Xero — with invoices, statements, quotes, credit notes and Pay Now.",
    category: "xero",
    summary:
      "Portal Genie connects to Xero to bring contacts, invoices, statements, quotes and credit notes into a branded Client Portal for your clients.",
    keywords: [
      "xero client portal",
      "xero integration",
      "xero invoices",
      "xero connected app",
    ],
    relatedArticles: [
      "accounting-integrations",
      "client-portal-payments",
      "client-portal-access",
    ],
    relatedPages: [links.features, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "quickbooks-client-portal",
    slug: "quickbooks-client-portal",
    title: "Portal Genie for QuickBooks Online",
    description:
      "Connect QuickBooks Online to deliver a branded Client Portal with accounting documents and secure client access.",
    category: "quickbooks",
    summary:
      "Portal Genie integrates with QuickBooks Online to surface accounting documents and client contacts in your Client Portal.",
    keywords: [
      "quickbooks client portal",
      "quickbooks online",
      "accounting integration",
    ],
    relatedArticles: [
      "accounting-integrations",
      "client-portal-payments",
      "share-client-documents",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "sage-client-portal",
    slug: "sage-client-portal",
    title: "Portal Genie for Sage Business Cloud",
    description:
      "Connect Sage Business Cloud to deliver accounting documents and secure client access through your Client Portal.",
    category: "sage",
    summary:
      "Portal Genie integrates with Sage Business Cloud to bring accounting documents and client records into your branded Client Portal.",
    keywords: [
      "sage client portal",
      "sage business cloud",
      "accounting integration",
    ],
    relatedArticles: [
      "accounting-integrations",
      "client-portal-payments",
      "share-client-documents",
    ],
    relatedPages: [links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-payments",
    slug: "client-portal-payments",
    title: "Let Clients Pay Invoices Through the Client Portal",
    description:
      "Enable Pay Now so clients can pay invoices online through your Client Portal via Stripe or Peach Payments.",
    category: "payments",
    summary:
      "Clients select invoices and pay through Pay Now in your Client Portal when you connect a supported payment provider such as Stripe or Peach Payments.",
    keywords: [
      "pay now",
      "online payments",
      "stripe",
      "peach payments",
      "invoice payments",
    ],
    relatedArticles: [
      "xero-client-portal",
      "client-portal-features",
      "accounting-integrations",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-branding",
    slug: "client-portal-branding",
    title: "Brand the Client Portal as Your Own",
    description:
      "Present a professional, on-brand Client Portal with your logo, colours and welcome messaging.",
    category: "branding",
    summary:
      "Apply your logo, brand colours and welcome messaging so your Client Portal feels like a natural extension of your business.",
    keywords: [
      "portal branding",
      "logo",
      "brand colours",
      "white label",
    ],
    relatedArticles: [
      "custom-client-portal-domain",
      "customise-client-portal",
      "core-vs-pro",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "custom-client-portal-domain",
    slug: "custom-client-portal-domain",
    title: "Using Your Own Client Portal Domain",
    description:
      "Use your own portal web address on Pro — such as portal.yourcompany.com — for a fully branded client experience.",
    category: "branding",
    summary:
      "Pro lets you use your own portal web address, such as portal.yourcompany.com, so clients access your portal on a domain they recognise.",
    keywords: [
      "custom domain",
      "portal web address",
      "branded portal",
      "pro feature",
    ],
    relatedArticles: [
      "client-portal-branding",
      "core-vs-pro",
      "client-portal-security",
    ],
    relatedPages: [links.pricing, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "scheduled-client-notifications",
    slug: "scheduled-client-notifications",
    title: "Scheduled Client Email Notifications",
    description:
      "Schedule client email campaigns on Pro — with client groups, custom content and included email allowance.",
    category: "notifications",
    summary:
      "Pro includes scheduled email campaigns so you can send targeted communications to client groups, with 3,000 emails included per month.",
    keywords: [
      "email campaigns",
      "scheduled notifications",
      "client groups",
      "pro feature",
    ],
    relatedArticles: [
      "new-document-notifications",
      "core-vs-pro",
      "document-notes",
    ],
    relatedPages: [links.pricing, links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-security",
    slug: "client-portal-security",
    title: "How Portal Genie Keeps Client Portal Access Secure",
    description:
      "Learn how secure OTP access, user permissions and optional portal password protection help keep your Client Portal secure.",
    category: "security",
    summary:
      "Clients access your portal through secure email OTP verification, with optional extra password protection on Pro and role-based permissions for your team.",
    keywords: [
      "portal security",
      "OTP access",
      "user permissions",
      "secure access",
    ],
    relatedArticles: [
      "client-portal-access",
      "users-and-permissions",
      "custom-client-portal-domain",
    ],
    relatedPages: [links.features, links.contact],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "users-and-permissions",
    slug: "users-and-permissions",
    title: "Managing Team Users and Permissions",
    description:
      "Add team members, assign roles and control what each user can access in your Portal Genie account.",
    category: "security",
    summary:
      "Manage your team with role-based permissions. Core and Pro include 2 users, with additional users available as your team grows.",
    keywords: [
      "users",
      "permissions",
      "team access",
      "roles",
    ],
    relatedArticles: [
      "client-portal-security",
      "core-vs-pro",
    ],
    relatedPages: [links.pricing, links.contact],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "core-vs-pro",
    slug: "core-vs-pro",
    title: "Portal Genie Core vs Pro",
    description:
      "Compare Core and Pro plans to find the right Client Portal features, storage and communication tools for your business.",
    category: "plans",
    summary:
      "Core delivers the complete client portal experience. Pro adds custom domains, client uploads, document notes, scheduled emails and more.",
    keywords: [
      "core vs pro",
      "pricing plans",
      "plan comparison",
      "client portal plans",
    ],
    relatedArticles: [
      "client-portal-branding",
      "client-document-uploads",
      "scheduled-client-notifications",
    ],
    relatedPages: [links.pricing, links.pricingPlans, links.bookDemo],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "client-portal-analytics",
    slug: "client-portal-analytics",
    title: "Understanding Client Portal Engagement",
    description:
      "Track portal visits, mobile and desktop usage, and Notice Board interactions to understand client engagement.",
    category: "analytics",
    summary:
      "Monitor portal visits, mobile and desktop access, and Notice Board click activity to understand how clients engage with your portal.",
    keywords: [
      "portal analytics",
      "client engagement",
      "portal visits",
      "notice board clicks",
    ],
    relatedArticles: [
      "notice-board",
      "client-portal-features",
    ],
    relatedPages: [links.features, links.customerSuccess],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
  {
    id: "archive-hide-customers",
    slug: "archive-hide-customers",
    title: "Can I hide or archive customers in The Portal Genie?",
    description:
      "Learn how customer records are imported into The Portal Genie, whether individual customers can currently be hidden or archived, and how to manage inactive customers.",
    category: "communication",
    summary:
      "Customer records are imported from your accounting software. Individual customers cannot currently be hidden or archived, but you can exclude inactive clients from scheduled communications.",
    keywords: [
      "hide customer",
      "hide client",
      "block customer",
      "block client",
      "remove customer",
      "remove client",
      "delete customer",
      "archive customer",
      "archive client",
      "inactive customer",
      "inactive client",
      "dormant customer",
      "old customer",
      "former customer",
      "exclude customer",
      "exclude client",
      "customer list",
      "client list",
    ],
    relatedArticles: ["email-selected-customers", "scheduled-client-notifications"],
    relatedPages: [links.contact, links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-16",
    updatedAt: "2026-08-16",
  },
  {
    id: "supplier-appearing-as-customer",
    slug: "supplier-appearing-as-customer",
    title: "Why is a supplier appearing in my customer list?",
    description:
      "Find out what to do if a supplier from your accounting software appears as a customer in The Portal Genie.",
    category: "integrations",
    summary:
      "Suppliers are normally excluded from the client import. If a supplier appears as a customer, contact Portal Genie support so the import can be investigated.",
    keywords: [
      "supplier showing as customer",
      "supplier appearing as customer",
      "supplier in customer list",
      "supplier in client list",
      "vendor showing as customer",
      "customer import",
      "client import",
      "accounting software customer import",
    ],
    relatedArticles: ["archive-hide-customers", "accounting-integrations"],
    relatedPages: [links.contact],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-16",
    updatedAt: "2026-08-16",
  },
  {
    id: "email-selected-customers",
    slug: "email-selected-customers",
    title: "How can I send portal emails only to selected customers?",
    description:
      "Use Scheduled Email and Import XLS to target portal communications to selected customers while excluding inactive clients.",
    category: "notifications",
    summary:
      "Create a Scheduled Email template, then use Import XLS from the Clients table to bulk assign it to specific clients and exclude inactive customers.",
    keywords: [
      "send emails to selected customers",
      "email selected clients",
      "exclude customers from emails",
      "exclude clients from emails",
      "scheduled email",
      "Import XLS",
      "bulk assign email template",
      "inactive customer",
      "inactive client",
      "customer list",
      "client list",
    ],
    relatedArticles: [
      "archive-hide-customers",
      "scheduled-client-notifications",
      "new-document-notifications",
    ],
    relatedPages: [links.features, links.pricing],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-16",
    updatedAt: "2026-08-16",
  },
  {
    id: "faq",
    slug: "faq",
    title: "Portal Genie Frequently Asked Questions",
    description:
      "Answers to common questions about The Portal Genie Client Portal — access, features, integrations, plans and more.",
    category: "faq",
    summary:
      "Quick answers about client access, website login, accounting integrations, payments, customisation and Core vs Pro.",
    keywords: [
      "faq",
      "frequently asked questions",
      "portal genie help",
      "client portal questions",
    ],
    relatedArticles: [
      "what-is-the-portal-genie",
      "client-portal-access",
      "add-client-login-to-your-website",
      "core-vs-pro",
    ],
    relatedPages: [links.pricing, links.bookDemo, links.features],
    public: true,
    botEnabled: true,
    indexable: true,
    lastReviewed: "2026-08-14",
    updatedAt: "2026-08-14",
  },
] as const;

validateKnowledgeRegistry(knowledgeArticles);
