export const links = {
  home: "/",
  whyThePortalGenie: "/why-the-portal-genie",
  platform: "/platform",
  features: "/features",
  pricing: "/pricing",
  resources: "/resources",
  customerSuccess: "/customer-success",
  contact: "/contact",
  documentation: "/documentation",
  productUpdates: "/product-updates",
  faq: "/faq",
  privacyPolicy: "/privacy-policy",
  termsAndConditions: "/terms-and-conditions",
  youtube: "/youtube",
  bookDemo: "/book-a-demo",
  login: "https://app.theportalgenie.com/app/login",
  startFree: "/start-free",
  support: "/contact",
} as const;
